spring:
  application:
    name: extrator-dados
  datasource:
    url: jdbc:postgresql://localhost:5432/extrator_dados
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: 8080

logging:
  level:
    com.empresa.extrator: DEBUG
    org.springframework.security: DEBUG